import './globals.css'
import Header from '@/app/_components/Header'
import PostNav from '@/app/_components/PostNav'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={inter.className}>
                <Header />
                <PostNav />
                <main className='mx-auto w-full max-w-[1200px]'>
                    {children}
                </main>
            </body>
        </html>
    )
}
