import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import Header from '@/app/_components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    metadataBase: new URL('https://duckblog-d51wyx48f-littleduck1219s-projects.vercel.app/blog'),

    appleWebApp: {
        capable: true,
        statusBarStyle: 'default',
        // startUpImage: [],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <head>
                <meta name='apple-mobile-web-app-capable' content='yes' />
            </head>
            <body className={inter.className}>
                <Header />
                <main className=''>{children}</main>
            </body>
        </html>
    );
}
